[build]
  command = "pip install -r requirements.txt"
  publish = "frontend/build"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-python" 