[build]
  command = "pip install -r requirements.txt && npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
